---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 736b3974f10de2c01f639c7b2bc29c07b03044a7
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: main
    prometheus.io/scrape: "true"
    prometheus.io/port: "9779"
  labels:
    expose: "true"
    app: proxy-data-info
    provider: fabric8
    version: "1.0"
    group: co.data.info
  name: proxy-data-info
spec:
  ports:
  - name: tcp-1
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: proxy-data-info
    provider: fabric8
    group: co.data.info
  type: ClusterIP
